请求网址
https://www.tapd.cn/api/testx/plan/v1/namespaces/33142026/plans/152227/cases-search
请求方法
POST
入参：
{"ShowMode":"TREE","Version":"V2","StoryShowMode":"TREE","WithCaseReviewState":true}

返参：
{
    "Error": null,
    "Data": {
        "Folders": [],
        "Cases": [],
        "CaseUidToDetail": {},
        "PlanCasesInfo": {
            "StoryGroup": [
                {
                    "Story": {
                        "IssueUid": "1133142026001000041",
                        "Namespace": "33142026",
                        "WorkspaceUid": "33142026",
                        "IssueUrl": "",
                        "Type": "STORY",
                        "Source": "NONE",
                        "Detail": {
                            "CategoryId": "1133142026001000010",
                            "Completed": "0",
                            "Created": "2025-07-15 09:47:47",
                            "Creator": "TAPD",
                            "CustomFields": {
                                "custom_field_10": "",
                                "custom_field_100": "",
                                "custom_field_101": "",
                                "custom_field_102": "",
                                "custom_field_103": "",
                                "custom_field_104": "",
                                "custom_field_105": "",
                                "custom_field_106": "",
                                "custom_field_107": "",
                                "custom_field_108": "",
                                "custom_field_109": "",
                                "custom_field_11": "",
                                "custom_field_110": "",
                                "custom_field_111": "",
                                "custom_field_112": "",
                                "custom_field_113": "",
                                "custom_field_114": "",
                                "custom_field_115": "",
                                "custom_field_116": "",
                                "custom_field_117": "",
                                "custom_field_118": "",
                                "custom_field_119": "",
                                "custom_field_12": "",
                                "custom_field_120": "",
                                "custom_field_121": "",
                                "custom_field_122": "",
                                "custom_field_123": "",
                                "custom_field_124": "",
                                "custom_field_125": "",
                                "custom_field_126": "",
                                "custom_field_127": "",
                                "custom_field_128": "",
                                "custom_field_129": "",
                                "custom_field_13": "",
                                "custom_field_130": "",
                                "custom_field_131": "",
                                "custom_field_132": "",
                                "custom_field_133": "",
                                "custom_field_134": "",
                                "custom_field_135": "",
                                "custom_field_136": "",
                                "custom_field_137": "",
                                "custom_field_138": "",
                                "custom_field_139": "",
                                "custom_field_14": "",
                                "custom_field_140": "",
                                "custom_field_141": "",
                                "custom_field_142": "",
                                "custom_field_143": "",
                                "custom_field_144": "",
                                "custom_field_145": "",
                                "custom_field_146": "",
                                "custom_field_147": "",
                                "custom_field_148": "",
                                "custom_field_149": "",
                                "custom_field_15": "",
                                "custom_field_150": "",
                                "custom_field_151": "",
                                "custom_field_152": "",
                                "custom_field_153": "",
                                "custom_field_154": "",
                                "custom_field_155": "",
                                "custom_field_156": "",
                                "custom_field_157": "",
                                "custom_field_158": "",
                                "custom_field_159": "",
                                "custom_field_16": "",
                                "custom_field_160": "",
                                "custom_field_161": "",
                                "custom_field_162": "",
                                "custom_field_163": "",
                                "custom_field_164": "",
                                "custom_field_165": "",
                                "custom_field_166": "",
                                "custom_field_167": "",
                                "custom_field_168": "",
                                "custom_field_169": "",
                                "custom_field_17": "",
                                "custom_field_170": "",
                                "custom_field_171": "",
                                "custom_field_172": "",
                                "custom_field_173": "",
                                "custom_field_174": "",
                                "custom_field_175": "",
                                "custom_field_176": "",
                                "custom_field_177": "",
                                "custom_field_178": "",
                                "custom_field_179": "",
                                "custom_field_18": "",
                                "custom_field_180": "",
                                "custom_field_181": "",
                                "custom_field_182": "",
                                "custom_field_183": "",
                                "custom_field_184": "",
                                "custom_field_185": "",
                                "custom_field_186": "",
                                "custom_field_187": "",
                                "custom_field_188": "",
                                "custom_field_189": "",
                                "custom_field_19": "",
                                "custom_field_190": "",
                                "custom_field_191": "",
                                "custom_field_192": "",
                                "custom_field_193": "",
                                "custom_field_194": "",
                                "custom_field_195": "",
                                "custom_field_196": "",
                                "custom_field_197": "",
                                "custom_field_198": "",
                                "custom_field_199": "",
                                "custom_field_20": "",
                                "custom_field_200": "",
                                "custom_field_21": "",
                                "custom_field_22": "",
                                "custom_field_23": "",
                                "custom_field_24": "",
                                "custom_field_25": "",
                                "custom_field_26": "",
                                "custom_field_27": "",
                                "custom_field_28": "",
                                "custom_field_29": "",
                                "custom_field_30": "",
                                "custom_field_31": "",
                                "custom_field_32": "",
                                "custom_field_33": "",
                                "custom_field_34": "",
                                "custom_field_35": "",
                                "custom_field_36": "",
                                "custom_field_37": "",
                                "custom_field_38": "",
                                "custom_field_39": "",
                                "custom_field_40": "",
                                "custom_field_41": "",
                                "custom_field_42": "",
                                "custom_field_43": "",
                                "custom_field_44": "",
                                "custom_field_45": "",
                                "custom_field_46": "",
                                "custom_field_47": "",
                                "custom_field_48": "",
                                "custom_field_49": "",
                                "custom_field_50": "",
                                "custom_field_51": "",
                                "custom_field_52": "",
                                "custom_field_53": "",
                                "custom_field_54": "",
                                "custom_field_55": "",
                                "custom_field_56": "",
                                "custom_field_57": "",
                                "custom_field_58": "",
                                "custom_field_59": "",
                                "custom_field_60": "",
                                "custom_field_61": "",
                                "custom_field_62": "",
                                "custom_field_63": "",
                                "custom_field_64": "",
                                "custom_field_65": "",
                                "custom_field_66": "",
                                "custom_field_67": "",
                                "custom_field_68": "",
                                "custom_field_69": "",
                                "custom_field_70": "",
                                "custom_field_71": "",
                                "custom_field_72": "",
                                "custom_field_73": "",
                                "custom_field_74": "",
                                "custom_field_75": "",
                                "custom_field_76": "",
                                "custom_field_77": "",
                                "custom_field_78": "",
                                "custom_field_79": "",
                                "custom_field_80": "",
                                "custom_field_81": "",
                                "custom_field_82": "",
                                "custom_field_83": "",
                                "custom_field_84": "",
                                "custom_field_85": "",
                                "custom_field_86": "",
                                "custom_field_87": "",
                                "custom_field_88": "",
                                "custom_field_89": "",
                                "custom_field_9": "",
                                "custom_field_90": "",
                                "custom_field_91": "",
                                "custom_field_92": "",
                                "custom_field_93": "",
                                "custom_field_94": "",
                                "custom_field_95": "",
                                "custom_field_96": "",
                                "custom_field_97": "",
                                "custom_field_98": "",
                                "custom_field_99": "",
                                "custom_field_eight": "",
                                "custom_field_five": "",
                                "custom_field_four": "",
                                "custom_field_one": "",
                                "custom_field_seven": "",
                                "custom_field_six": "",
                                "custom_field_three": "",
                                "custom_field_two": "",
                                "custom_plan_field_1": "0",
                                "custom_plan_field_10": "0",
                                "custom_plan_field_2": "0",
                                "custom_plan_field_3": "0",
                                "custom_plan_field_4": "0",
                                "custom_plan_field_5": "0",
                                "custom_plan_field_6": "0",
                                "custom_plan_field_7": "0",
                                "custom_plan_field_8": "0",
                                "custom_plan_field_9": "0"
                            },
                            "EndDate": "2025-07-18",
                            "Exceed": "0",
                            "Id": "1133142026001000041",
                            "IterationId": "1133142026001000004",
                            "Modified": "2025-07-15 09:47:47",
                            "ParentId": "1133142026001000032",
                            "Priority": {
                                "Label": "High",
                                "Value": "High"
                            },
                            "ReleaseID": "0",
                            "Remain": "0",
                            "StartDate": "2025-06-05",
                            "Status": {
                                "Label": "规划中",
                                "StatusRaw": "PLANNING",
                                "Value": "PLANNING"
                            },
                            "Summary": "【示例】邮箱密码登陆",
                            "TemplatedId": "1133142026001000010",
                            "WorkitemTypeId": "1133142026001000007",
                            "WorkspaceId": "33142026"
                        },
                        "IssueName": "",
                        "IsDeleted": false,
                        "Uid": ""
                    },
                    "Cases": [],
                    "Folders": [],
                    "ExecCaseCount": 0
                }
            ],
            "RepoVersionGroup": []
        }
    },
    "TotalCount": 0
}




请求网址
https://www.tapd.cn/api/testx/design/v2/namespaces/33142026/workspaces/33142026/stories?Ids=1133142026001000041
请求方法
GET
入参：
Ids=1133142026001000041
返参：
{
    "Error": null,
    "Data": [
        {
            "WorkspaceId": "33142026",
            "IterationId": "1133142026001000004",
            "Id": "1133142026001000041",
            "Summary": "【示例】邮箱密码登陆",
            "Creator": "TAPD",
            "Priority": {
                "Label": "High",
                "Value": "High"
            },
            "Status": {
                "Label": "规划中",
                "Value": "PLANNING",
                "StatusRaw": "PLANNING"
            },
            "Owners": "",
            "Created": "2025-07-15 09:47:47",
            "Modified": "2025-07-15 09:47:47",
            "Completed": "0",
            "StartDate": "2025-06-05",
            "EndDate": "2025-07-18",
            "NamespaceId": "",
            "Description": "",
            "Url": "",
            "Tags": [],
            "Children": [],
            "IconType": "",
            "StatusType": "",
            "Version": [],
            "Branchs": [],
            "CustomFields": {
                "custom_field_10": "",
                "custom_field_100": "",
                "custom_field_101": "",
                "custom_field_102": "",
                "custom_field_103": "",
                "custom_field_104": "",
                "custom_field_105": "",
                "custom_field_106": "",
                "custom_field_107": "",
                "custom_field_108": "",
                "custom_field_109": "",
                "custom_field_11": "",
                "custom_field_110": "",
                "custom_field_111": "",
                "custom_field_112": "",
                "custom_field_113": "",
                "custom_field_114": "",
                "custom_field_115": "",
                "custom_field_116": "",
                "custom_field_117": "",
                "custom_field_118": "",
                "custom_field_119": "",
                "custom_field_12": "",
                "custom_field_120": "",
                "custom_field_121": "",
                "custom_field_122": "",
                "custom_field_123": "",
                "custom_field_124": "",
                "custom_field_125": "",
                "custom_field_126": "",
                "custom_field_127": "",
                "custom_field_128": "",
                "custom_field_129": "",
                "custom_field_13": "",
                "custom_field_130": "",
                "custom_field_131": "",
                "custom_field_132": "",
                "custom_field_133": "",
                "custom_field_134": "",
                "custom_field_135": "",
                "custom_field_136": "",
                "custom_field_137": "",
                "custom_field_138": "",
                "custom_field_139": "",
                "custom_field_14": "",
                "custom_field_140": "",
                "custom_field_141": "",
                "custom_field_142": "",
                "custom_field_143": "",
                "custom_field_144": "",
                "custom_field_145": "",
                "custom_field_146": "",
                "custom_field_147": "",
                "custom_field_148": "",
                "custom_field_149": "",
                "custom_field_15": "",
                "custom_field_150": "",
                "custom_field_151": "",
                "custom_field_152": "",
                "custom_field_153": "",
                "custom_field_154": "",
                "custom_field_155": "",
                "custom_field_156": "",
                "custom_field_157": "",
                "custom_field_158": "",
                "custom_field_159": "",
                "custom_field_16": "",
                "custom_field_160": "",
                "custom_field_161": "",
                "custom_field_162": "",
                "custom_field_163": "",
                "custom_field_164": "",
                "custom_field_165": "",
                "custom_field_166": "",
                "custom_field_167": "",
                "custom_field_168": "",
                "custom_field_169": "",
                "custom_field_17": "",
                "custom_field_170": "",
                "custom_field_171": "",
                "custom_field_172": "",
                "custom_field_173": "",
                "custom_field_174": "",
                "custom_field_175": "",
                "custom_field_176": "",
                "custom_field_177": "",
                "custom_field_178": "",
                "custom_field_179": "",
                "custom_field_18": "",
                "custom_field_180": "",
                "custom_field_181": "",
                "custom_field_182": "",
                "custom_field_183": "",
                "custom_field_184": "",
                "custom_field_185": "",
                "custom_field_186": "",
                "custom_field_187": "",
                "custom_field_188": "",
                "custom_field_189": "",
                "custom_field_19": "",
                "custom_field_190": "",
                "custom_field_191": "",
                "custom_field_192": "",
                "custom_field_193": "",
                "custom_field_194": "",
                "custom_field_195": "",
                "custom_field_196": "",
                "custom_field_197": "",
                "custom_field_198": "",
                "custom_field_199": "",
                "custom_field_20": "",
                "custom_field_200": "",
                "custom_field_21": "",
                "custom_field_22": "",
                "custom_field_23": "",
                "custom_field_24": "",
                "custom_field_25": "",
                "custom_field_26": "",
                "custom_field_27": "",
                "custom_field_28": "",
                "custom_field_29": "",
                "custom_field_30": "",
                "custom_field_31": "",
                "custom_field_32": "",
                "custom_field_33": "",
                "custom_field_34": "",
                "custom_field_35": "",
                "custom_field_36": "",
                "custom_field_37": "",
                "custom_field_38": "",
                "custom_field_39": "",
                "custom_field_40": "",
                "custom_field_41": "",
                "custom_field_42": "",
                "custom_field_43": "",
                "custom_field_44": "",
                "custom_field_45": "",
                "custom_field_46": "",
                "custom_field_47": "",
                "custom_field_48": "",
                "custom_field_49": "",
                "custom_field_50": "",
                "custom_field_51": "",
                "custom_field_52": "",
                "custom_field_53": "",
                "custom_field_54": "",
                "custom_field_55": "",
                "custom_field_56": "",
                "custom_field_57": "",
                "custom_field_58": "",
                "custom_field_59": "",
                "custom_field_60": "",
                "custom_field_61": "",
                "custom_field_62": "",
                "custom_field_63": "",
                "custom_field_64": "",
                "custom_field_65": "",
                "custom_field_66": "",
                "custom_field_67": "",
                "custom_field_68": "",
                "custom_field_69": "",
                "custom_field_70": "",
                "custom_field_71": "",
                "custom_field_72": "",
                "custom_field_73": "",
                "custom_field_74": "",
                "custom_field_75": "",
                "custom_field_76": "",
                "custom_field_77": "",
                "custom_field_78": "",
                "custom_field_79": "",
                "custom_field_80": "",
                "custom_field_81": "",
                "custom_field_82": "",
                "custom_field_83": "",
                "custom_field_84": "",
                "custom_field_85": "",
                "custom_field_86": "",
                "custom_field_87": "",
                "custom_field_88": "",
                "custom_field_89": "",
                "custom_field_9": "",
                "custom_field_90": "",
                "custom_field_91": "",
                "custom_field_92": "",
                "custom_field_93": "",
                "custom_field_94": "",
                "custom_field_95": "",
                "custom_field_96": "",
                "custom_field_97": "",
                "custom_field_98": "",
                "custom_field_99": "",
                "custom_field_eight": "",
                "custom_field_five": "",
                "custom_field_four": "",
                "custom_field_one": "",
                "custom_field_seven": "",
                "custom_field_six": "",
                "custom_field_three": "",
                "custom_field_two": "",
                "custom_plan_field_1": "0",
                "custom_plan_field_10": "0",
                "custom_plan_field_2": "0",
                "custom_plan_field_3": "0",
                "custom_plan_field_4": "0",
                "custom_plan_field_5": "0",
                "custom_plan_field_6": "0",
                "custom_plan_field_7": "0",
                "custom_plan_field_8": "0",
                "custom_plan_field_9": "0"
            },
            "CC": "",
            "Developer": "",
            "Effort": "",
            "Remain": "0",
            "Exceed": "0",
            "ReleaseID": "0",
            "BusinessValue": "",
            "Module": "",
            "TestFocus": "",
            "Size": "",
            "TemplatedId": "1133142026001000010",
            "ParentId": "1133142026001000032",
            "CategoryId": "1133142026001000010",
            "WorkitemTypeId": "1133142026001000007",
            "Feature": "",
            "TechRisk": "",
            "CustomPlanFields": {},
            "IsApplyTemplateDefaultValue": false,
            "TapdVersion": ""
        }
    ],
    "TotalCount": 1,
    "RequestId": "712deb6c097bbf6e1720bbdbe3949aa5"
}



根据上述内容设计MySQL5 的表结构（可能涉及多个表）， 需要带上完整的备注内容。
确保语法合法 。 不要漏掉吧表。 我需要完整的ddl以及一两条测试数据

-- =============================
-- 测试计划用例执行相关表结构 DDL
-- =============================

-- 计划用例主表
CREATE TABLE IF NOT EXISTS `plan_case_executes` (
  `id` VARCHAR(32) NOT NULL COMMENT '计划用例执行唯一ID',
  `plan_uid` VARCHAR(32) NOT NULL COMMENT '所属测试计划ID',
  `story_uid` VARCHAR(32) NOT NULL COMMENT '需求/故事ID',
  `workspace_id` VARCHAR(32) NOT NULL COMMENT '工作区ID',
  `iteration_id` VARCHAR(32) DEFAULT '' COMMENT '迭代ID',
  `summary` VARCHAR(255) DEFAULT '' COMMENT '需求摘要',
  `creator` VARCHAR(32) DEFAULT '' COMMENT '创建人',
  `priority_label` VARCHAR(32) DEFAULT '' COMMENT '优先级标签',
  `priority_value` VARCHAR(32) DEFAULT '' COMMENT '优先级值',
  `status_label` VARCHAR(32) DEFAULT '' COMMENT '状态标签',
  `status_value` VARCHAR(32) DEFAULT '' COMMENT '状态值',
  `status_raw` VARCHAR(32) DEFAULT '' COMMENT '原始状态',
  `owners` VARCHAR(255) DEFAULT '' COMMENT '负责人',
  `created_at` DATETIME DEFAULT NULL COMMENT '创建时间',
  `modified_at` DATETIME DEFAULT NULL COMMENT '修改时间',
  `completed` TINYINT(1) DEFAULT 0 COMMENT '是否完成',
  `start_date` DATE DEFAULT NULL COMMENT '开始日期',
  `end_date` DATE DEFAULT NULL COMMENT '结束日期',
  `description` TEXT COMMENT '描述',
  `url` VARCHAR(255) DEFAULT '' COMMENT '需求链接',
  `cc` VARCHAR(255) DEFAULT '' COMMENT '抄送人',
  `developer` VARCHAR(255) DEFAULT '' COMMENT '开发人员',
  `effort` VARCHAR(32) DEFAULT '' COMMENT '工时',
  `remain` VARCHAR(32) DEFAULT '' COMMENT '剩余工时',
  `exceed` VARCHAR(32) DEFAULT '' COMMENT '超出工时',
  `release_id` VARCHAR(32) DEFAULT '' COMMENT '发布ID',
  `business_value` VARCHAR(255) DEFAULT '' COMMENT '业务价值',
  `module` VARCHAR(255) DEFAULT '' COMMENT '模块',
  `test_focus` VARCHAR(255) DEFAULT '' COMMENT '测试关注点',
  `size` VARCHAR(32) DEFAULT '' COMMENT '规模',
  `templated_id` VARCHAR(32) DEFAULT '' COMMENT '模板ID',
  `parent_id` VARCHAR(32) DEFAULT '' COMMENT '父ID',
  `category_id` VARCHAR(32) DEFAULT '' COMMENT '分类ID',
  `workitem_type_id` VARCHAR(32) DEFAULT '' COMMENT '工作项类型ID',
  `feature` VARCHAR(255) DEFAULT '' COMMENT '特性',
  `tech_risk` VARCHAR(255) DEFAULT '' COMMENT '技术风险',
  `is_apply_template_default_value` TINYINT(1) DEFAULT 0 COMMENT '是否应用模板默认值',
  `tapd_version` VARCHAR(64) DEFAULT '' COMMENT 'TAPD版本',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='测试计划用例执行主表';

-- 计划用例自定义字段表（EAV模型）
CREATE TABLE IF NOT EXISTS `plan_case_execute_custom_fields` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `plan_case_execute_id` VARCHAR(32) NOT NULL COMMENT '计划用例执行ID',
  `field_key` VARCHAR(64) NOT NULL COMMENT '自定义字段名，如custom_field_89',
  `field_value` TEXT COMMENT '自定义字段值',
  CONSTRAINT fk_plan_case_custom_field FOREIGN KEY (`plan_case_execute_id`) REFERENCES `plan_case_executes`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='测试计划用例执行自定义字段';

-- 测试数据
INSERT INTO `plan_case_executes` (
  `id`, `plan_uid`, `story_uid`, `workspace_id`, `iteration_id`, `summary`, `creator`, `priority_label`, `priority_value`, `status_label`, `status_value`, `status_raw`, `owners`, `created_at`, `modified_at`, `completed`, `start_date`, `end_date`, `description`, `url`, `cc`, `developer`, `effort`, `remain`, `exceed`, `release_id`, `business_value`, `module`, `test_focus`, `size`, `templated_id`, `parent_id`, `category_id`, `workitem_type_id`, `feature`, `tech_risk`, `is_apply_template_default_value`, `tapd_version`
) VALUES (
  'exec-001', '152227', '1133142026001000041', '33142026', '1133142026001000004', '【示例】邮箱密码登陆', 'TAPD', 'High', 'High', '规划中', 'PLANNING', 'PLANNING', '', '2025-07-15 09:47:47', '2025-07-15 09:47:47', 0, '2025-06-05', '2025-07-18', '', '', '', '', '', '0', '0', '0', '0', '', '', '', '', '1133142026001000010', '1133142026001000032', '1133142026001000010', '1133142026001000007', '', '', 0, ''
);

INSERT INTO `plan_case_execute_custom_fields` (`plan_case_execute_id`, `field_key`, `field_value`) VALUES
('exec-001', 'custom_field_89', '自定义值示例'),
('exec-001', 'custom_field_10', '');

