# 文件导入导出模块默认配置
file:
  import:
    export:
      enabled: true
      import:
        max-batch-size: 20000
        max-files: 20
        concurrent: 1
      export:
        max-batch-size: 50000
        concurrent: 10
      path:
        upload-dir: ${file.import.export.path.upload-dir:C:\\Users\\lm\\Downloads\\uploads}
        export-dir: ${file.import.export.path.export-dir:C:\\Users\\lm\\Downloads\\exports}
      redis:
        key-prefix: "file-io"
        task-ttl: 86400
        
# 线程池配置
spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: "file-io-"