
请求网址
https://www.tapd.cn/api/entity/stories/quickly_create
请求方法
POST

{"workspace_id":"60498179","name":"【示例】校园小拍卖家应用1","workitem_type_id":"1160498179001000017","workitemTypeId":"1160498179001000017","owner":"","priority":"","entity_type":"story","parent_id":"1160498179001000078","category_id":"-1","useScene":"storyList","dsc_token":"B14PcWsEU6IsFDYQ"}


{
    "data": {
        "id": "1160498179001000147",
        "secret_root_id": "0",
        "sort": "100037300000",
        "workitem_type_id": "1160498179001000017",
        "name": "\u3010\u793a\u4f8b\u3011\u6821\u56ed\u5c0f\u62cd\u5356\u5bb6\u5e94\u75281",
        "description": "",
        "markdown_description": "",
        "description_type": "1",
        "creator": "\u672a\u547d\u540d\u5c0f\u7a0b\u5e8f",
        "created": "2025-06-13 09:49:13",
        "modified": "2025-06-13 09:49:13",
        "parent_id": "1160498179001000078",
        "children_id": "|",
        "ancestor_id": "1160498179001000078",
        "path": "1160498179001000078:1160498179001000147:",
        "level": "1",
        "workspace_id": "60498179",
        "status": "planning",
        "app_id": "1",
        "flows": "",
        "priority": "Middle",
        "owner": "",
        "participator": "",
        "cc": "",
        "begin": "",
        "due": "2025-07-12",
        "source": "",
        "workitem_id": "",
        "iteration_id": "0",
        "issue_id": "",
        "support_id": "",
        "support_forum_id": "",
        "module": "",
        "completed": "",
        "templated_id": "1160498179001000026",
        "delay_count": "",
        "type": "",
        "status_append": "",
        "business_value": "",
        "tech_risk": "",
        "size": "",
        "import_flag": "0",
        "effort": "",
        "effort_completed": "0",
        "exceed": "0",
        "remain": "0",
        "progress": "0",
        "release_id": "0",
        "feature": "",
        "entity_type": "Story",
        "custom_field_one": "",
        "custom_field_two": "",
        "custom_field_three": "",
        "custom_field_four": "",
        "custom_field_five": "",
        "custom_field_six": "",
        "custom_field_seven": "",
        "custom_field_eight": "",
        "attachment_count": "0",
        "has_attachment": "0",
        "developer": "",
        "bug_id": "",
        "test_focus": "",
        "category_id": "-1",
        "version": "",
        "confidential": "N",
        "created_from": "",
        "follower": "",
        "sync_type": "",
        "predecessor_count": "0",
        "is_archived": "0",
        "modifier": "",
        "progress_manual": "0",
        "successor_count": "0",
        "label": "",
        "step": "",
        "custom_field_9": "",
        "custom_field_10": "",
        "custom_field_11": "",
        "custom_field_12": "",
        "custom_field_13": "",
        "custom_field_14": "",
        "custom_field_15": "",
        "custom_field_16": "",
        "custom_field_17": "",
        "custom_field_18": "",
        "custom_field_19": "",
        "custom_field_20": "",
        "custom_field_21": "",
        "custom_field_22": "",
        "custom_field_23": "",
        "custom_field_24": "",
        "custom_field_25": "",
        "custom_field_26": "",
        "custom_field_27": "",
        "custom_field_28": "",
        "custom_field_29": "",
        "custom_field_30": "",
        "custom_field_31": "",
        "custom_field_32": "",
        "custom_field_33": "",
        "custom_field_34": "",
        "custom_field_35": "",
        "custom_field_36": "",
        "custom_field_37": "",
        "custom_field_38": "",
        "custom_field_39": "",
        "custom_field_40": "",
        "custom_field_41": "",
        "custom_field_42": "",
        "custom_field_43": "",
        "custom_field_44": "",
        "custom_field_45": "",
        "custom_field_46": "",
        "custom_field_47": "",
        "custom_field_48": "",
        "custom_field_49": "",
        "custom_field_50": "",
        "custom_field_51": "",
        "custom_field_52": "",
        "custom_field_53": "",
        "custom_field_54": "",
        "custom_field_55": "",
        "custom_field_56": "",
        "custom_field_57": "",
        "custom_field_58": "",
        "custom_field_59": "",
        "custom_field_60": "",
        "custom_field_61": "",
        "custom_field_62": "",
        "custom_field_63": "",
        "custom_field_64": "",
        "custom_field_65": "",
        "custom_field_66": "",
        "custom_field_67": "",
        "custom_field_68": "",
        "custom_field_69": "",
        "custom_field_70": "",
        "custom_field_71": "",
        "custom_field_72": "",
        "custom_field_73": "",
        "custom_field_74": "",
        "custom_field_75": "",
        "custom_field_76": "",
        "custom_field_77": "",
        "custom_field_78": "",
        "custom_field_79": "",
        "custom_field_80": "",
        "custom_field_81": "",
        "custom_field_82": "",
        "custom_field_83": "",
        "custom_field_84": "",
        "custom_field_85": "",
        "custom_field_86": "",
        "custom_field_87": "",
        "custom_field_88": "",
        "custom_field_89": "",
        "custom_field_90": "",
        "custom_field_91": "",
        "custom_field_92": "",
        "custom_field_93": "",
        "custom_field_94": "",
        "custom_field_95": "",
        "custom_field_96": "",
        "custom_field_97": "",
        "custom_field_98": "",
        "custom_field_99": "",
        "custom_field_100": "",
        "custom_field_101": "",
        "custom_field_102": "",
        "custom_field_103": "",
        "custom_field_104": "",
        "custom_field_105": "",
        "custom_field_106": "",
        "custom_field_107": "",
        "custom_field_108": "",
        "custom_field_109": "",
        "custom_field_110": "",
        "custom_field_111": "",
        "custom_field_112": "",
        "custom_field_113": "",
        "custom_field_114": "",
        "custom_field_115": "",
        "custom_field_116": "",
        "custom_field_117": "",
        "custom_field_118": "",
        "custom_field_119": "",
        "custom_field_120": "",
        "custom_field_121": "",
        "custom_field_122": "",
        "custom_field_123": "",
        "custom_field_124": "",
        "custom_field_125": "",
        "custom_field_126": "",
        "custom_field_127": "",
        "custom_field_128": "",
        "custom_field_129": "",
        "custom_field_130": "",
        "custom_field_131": "",
        "custom_field_132": "",
        "custom_field_133": "",
        "custom_field_134": "",
        "custom_field_135": "",
        "custom_field_136": "",
        "custom_field_137": "",
        "custom_field_138": "",
        "custom_field_139": "",
        "custom_field_140": "",
        "custom_field_141": "",
        "custom_field_142": "",
        "custom_field_143": "",
        "custom_field_144": "",
        "custom_field_145": "",
        "custom_field_146": "",
        "custom_field_147": "",
        "custom_field_148": "",
        "custom_field_149": "",
        "custom_field_150": "",
        "custom_field_151": "",
        "custom_field_152": "",
        "custom_field_153": "",
        "custom_field_154": "",
        "custom_field_155": "",
        "custom_field_156": "",
        "custom_field_157": "",
        "custom_field_158": "",
        "custom_field_159": "",
        "custom_field_160": "",
        "custom_field_161": "",
        "custom_field_162": "",
        "custom_field_163": "",
        "custom_field_164": "",
        "custom_field_165": "",
        "custom_field_166": "",
        "custom_field_167": "",
        "custom_field_168": "",
        "custom_field_169": "",
        "custom_field_170": "",
        "custom_field_171": "",
        "custom_field_172": "",
        "custom_field_173": "",
        "custom_field_174": "",
        "custom_field_175": "",
        "custom_field_176": "",
        "custom_field_177": "",
        "custom_field_178": "",
        "custom_field_179": "",
        "custom_field_180": "",
        "custom_field_181": "",
        "custom_field_182": "",
        "custom_field_183": "",
        "custom_field_184": "",
        "custom_field_185": "",
        "custom_field_186": "",
        "custom_field_187": "",
        "custom_field_188": "",
        "custom_field_189": "",
        "custom_field_190": "",
        "custom_field_191": "",
        "custom_field_192": "",
        "custom_field_193": "",
        "custom_field_194": "",
        "custom_field_195": "",
        "custom_field_196": "",
        "custom_field_197": "",
        "custom_field_198": "",
        "custom_field_199": "",
        "custom_field_200": "",
        "custom_plan_field_1": "0",
        "custom_plan_field_2": "0",
        "custom_plan_field_3": "0",
        "custom_plan_field_4": "0",
        "custom_plan_field_5": "0",
        "custom_plan_field_6": "0",
        "custom_plan_field_7": "0",
        "custom_plan_field_8": "0",
        "custom_plan_field_9": "0",
        "custom_plan_field_10": "0",
        "workitem_type_english_name": "Featrue",
        "workitem_type_color": "#64c195",
        "workitem_type_name": "\u7279\u6027",
        "parent_name": "\u3010\u793a\u4f8b\u3011\u6821\u56ed\u5c0f\u62cd\u5356\u5bb6\u5e94\u7528",
        "short_id": "1000147",
        "enable_quickly_transfer": "",
        "step_delay_info": [],
        "step_period_info": [],
        "socket_login_data": {
            "socket_path": "https:\/\/spider.tapd.cn\/workitems",
            "login_data": {
                "user_nick": "\u672a\u547d\u540d\u5c0f\u7a0b\u5e8f::328519613",
                "workspace_id": "60498179",
                "timespan": "1749779354.2164043",
                "data_id": "workitems",
                "token": "ba95f83834a9e17733dc8d41adf9fc9aa4053883"
            },
            "room_ids": [
                "WORKITEMS_CHANGE_stories_list_328519613_1749779354_5873881"
            ],
            "socket_id": "60498179",
            "need_disconnect": "1"
        },
        "workspace_name": "\u5927\u578b\u56e2\u961f\u654f\u6377\u7814\u53d1"
    },
    "meta": {
        "code": "0",
        "message": "success"
    },
    "timestamp": "1749779354"
}

我需要mysql表设计。 ddl   dml


-- 主表：存储核心故事数据
CREATE TABLE tapd_stories (
    id BIGINT UNSIGNED PRIMARY KEY COMMENT '故事ID',
    workspace_id VARCHAR(20) NOT NULL COMMENT '空间ID',
    name VARCHAR(255) NOT NULL COMMENT '故事名称',
    workitem_type_id VARCHAR(30) NOT NULL COMMENT '工作项类型ID',
    entity_type ENUM('story', 'Story') NOT NULL DEFAULT 'story' COMMENT '实体类型',
    status VARCHAR(20) NOT NULL DEFAULT 'planning' COMMENT '状态',
    priority ENUM('', 'Middle') DEFAULT NULL COMMENT '优先级',
    parent_id VARCHAR(30) DEFAULT NULL COMMENT '父故事ID',
    short_id VARCHAR(20) COMMENT '短ID',
    created DATETIME NOT NULL COMMENT '创建时间',
    modified DATETIME NOT NULL COMMENT '修改时间',
    due_date DATE COMMENT '截止日期',
    description TEXT COMMENT '描述',
    attachment_count SMALLINT UNSIGNED DEFAULT 0 COMMENT '附件数',
    workspace_name VARCHAR(100) COMMENT '空间名称',
    INDEX idx_workspace (workspace_id),
    INDEX idx_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TAPD故事主表';

-- 自定义字段表 (动态存储200个字段)
CREATE TABLE tapd_custom_fields (
    story_id BIGINT UNSIGNED NOT NULL COMMENT '关联故事ID',
    field_num TINYINT UNSIGNED NOT NULL CHECK (field_num BETWEEN 1 AND 200) COMMENT '字段序号(1-200)',
    field_value VARCHAR(255) NOT NULL DEFAULT '' COMMENT '字段值',
    PRIMARY KEY (story_id, field_num),
    FOREIGN KEY (story_id) REFERENCES tapd_stories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故事自定义字段表';

-- 计划字段表
CREATE TABLE tapd_plan_fields (
    story_id BIGINT UNSIGNED NOT NULL COMMENT '关联故事ID',
    field_num TINYINT UNSIGNED NOT NULL CHECK (field_num BETWEEN 1 AND 10) COMMENT '字段序号(1-10)',
    field_value VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '字段值',
    PRIMARY KEY (story_id, field_num),
    FOREIGN KEY (story_id) REFERENCES tapd_stories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='故事计划字段表';

-- Socket嵌套数据表
CREATE TABLE tapd_socket_data (
    story_id BIGINT UNSIGNED PRIMARY KEY COMMENT '关联故事ID',
    socket_path VARCHAR(255) COMMENT 'Socket路径',
    user_nick VARCHAR(100) COMMENT '用户昵称',
    token VARCHAR(100) COMMENT '认证令牌',
    room_ids JSON COMMENT '房间ID数组',
    FOREIGN KEY (story_id) REFERENCES tapd_stories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Socket连接数据表';




INSERT INTO tapd_stories (
    id, workspace_id, name, workitem_type_id, entity_type,
    status, priority, parent_id, short_id, created, modified, due_date,
    attachment_count, workspace_name
) VALUES (
    1160498179001000147, 
    '60498179', 
    '【示例】校园小拍卖家应用1', 
    '1160498179001000017', 
    'Story', 
    'planning', 
    'Middle', 
    '1160498179001000078', 
    '1000147', 
    '2025-06-13 09:49:13', 
    '2025-06-13 09:49:13', 
    '2025-07-12', 
    0, 
    '大型团队敏捷研发'
);









