server:
  port: 8083
  servlet:
    context-path: /

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: ""
    enable-home-custom: false
    home-custom-path: ""
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2024-[Elasticsearch测试服务]
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: false
    enable-group: true
  cors: false
  production: false
  basic:
    enable: false

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: elasticsearch-test-service

# Elasticsearch CRUD 配置
elasticsearch:
  crud:
    enabled: true
    hosts:
      - localhost:9200
    # 如果ES有认证，请取消注释并配置
    # username: elastic
    # password: password
    connection-timeout: 5000
    socket-timeout: 60000
    request-timeout: 60000
    
    # 同步配置
    sync:
      batch-size: 1000
      thread-pool-size: 10
      retry-times: 3
    
    # 队列配置
    queue:
      type: redis
      redis:
        key-prefix: "es:sync:"
        max-retry: 3
        consumer-threads: 5
    
    # 租户配置
    tenant:
      enabled: false  # 暂时禁用租户功能进行基础测试
      index-prefix: "test_"
      auto-create-index: true
    
    # 索引配置
    index:
      use-keyword-as-default: true
      default-shards: 1
      default-replicas: 0

# Redis配置（用于队列）
spring:
  redis:
    host: localhost
    port: 6379
    # password: 如果有密码，请取消注释并填写
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 3000ms

# 日志配置
logging:
  level:
    root: INFO
    org.example: DEBUG
    com.example.elasticsearch: DEBUG
    org.elasticsearch: INFO
    org.springframework.data.elasticsearch: DEBUG