server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: my-test-execute
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tenant_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false

# 租户路由配置
tenant:
  routing:
    enabled: true
    header-name: X-Tenant-ID
    required: false  # 设置为false，这样没有租户ID也能访问
    exclude-paths: 
      - /swagger-ui.html
      - /doc.html
      - /actuator/**
      - /api/public/**
    tenant-center:
      url: jdbc:mysql://localhost:3306/tenant_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: password
    max-pool-size: 10
    min-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# 日志配置
logging:
  level:
    root: INFO
    com.tenant: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE