server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tenant_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  redis:
    host: 127.0.0.1
    port: 6379
    # password: yourpassword  # 如有密码请取消注释并填写

# Swagger认证配置
swagger:
  auth:
    username: admin
    password: admin123

# 全局租户拦截器配置
tenant:
  global-interceptor:
    enabled: false  # 是否启用全局租户拦截器
    header-name: X-Tenant-ID  # 租户ID请求头名称
    required: true  # 是否必需租户ID
    exclude-paths: /api/tenant/**,/swagger-ui.html,/doc.html,/druid/**,/v2/api-docs/**  # 排除的路径

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace 