CREATE TABLE `component_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `spc_id` bigint(20) NOT NULL COMMENT 'SPC ID',
  `component_code` varchar(50) DEFAULT NULL COMMENT '组件编码',
  `component_name` varchar(50) DEFAULT NULL COMMENT '组件名称',
  `component_eng_name` varchar(300) DEFAULT NULL COMMENT '组件英文名',
  `location` varchar(200) DEFAULT NULL COMMENT '位置信息',
  `architect` varchar(300) DEFAULT NULL COMMENT '架构师',
  `financial_code` varchar(100) DEFAULT NULL COMMENT '财务编码',
  `develop_dept` bigint(20) DEFAULT NULL COMMENT '研发部门',
  `develop_team` bigint(20) DEFAULT NULL COMMENT '开发团队',
  `develop_contact` varchar(50) DEFAULT NULL COMMENT '开发联系人',
  `develop_way` varchar(55) DEFAULT NULL COMMENT '开发方式',
  `test_dept` bigint(20) DEFAULT NULL COMMENT '测试部门',
  `test_team` bigint(20) DEFAULT NULL COMMENT '测试团队',
  `test_manager` varchar(300) DEFAULT NULL COMMENT '功能测试经理',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(50) DEFAULT NULL COMMENT '修改人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `ext_data` json DEFAULT NULL COMMENT '自定义字段',
  `default_solve_group_id` bigint(20) DEFAULT NULL COMMENT '默认解决组',
  `del_flag` varchar(2) DEFAULT NULL COMMENT '删除标记',
  `is_import` varchar(20) DEFAULT NULL COMMENT '是否导入',
  `tenant_id` bigint(22) DEFAULT NULL COMMENT '机构ID',
  `solve_group` varchar(20) DEFAULT NULL COMMENT '解决组',
  `component_status` varchar(20) DEFAULT NULL COMMENT '组件状态',
  `app_id` bigint(20) DEFAULT NULL COMMENT '应用ID',
  `assembly_no` varchar(255) DEFAULT NULL COMMENT '应用编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_spc_id` (`spc_id`),
  UNIQUE KEY `idx_component_code` (`component_code`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_assembly_no` (`assembly_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组件信息表';